/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RunnableDemo {
    private static boolean done = false;

    public static void main(String[] args) {
        Runnable hellos = () -> {
            for(int i = 1; i <= 1000; i++) {
                System.out.println("Hello " + i);
            }
            done = true;
        };
        Runnable goodbyes = () -> {
            for(int i = 1; i<= 1000; i++) {
                System.out.println("GoodBye " + i);
            }
            done = true;
        };

        ExecutorService executor = Executors.newCachedThreadPool();
        executor.execute(hellos);
        executor.execute(goodbyes);
        executor.shutdown();
    }
}
