/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core.java;

import java.util.Random;

/**
 * 자바 프로그램 컴파일 및 실행
 * 자바 프로그램은 두 단계를 거쳐 실행한다.
 * 1. javac 명령으로 자바 소스 코드를 특정 기계에 종속되지 않은 중간 표현인 바이트 코드로 컴파일해서 클래스 파일에 저장합니다.
 * 2. java 명령어로 가상 머신을 구동하고 클래스 파일을 로드해서 바이트 코드를 실행한다.
 */
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Hello World!!".length());// String 객체의 길이를 반환하는 length 메서드가 있다.

        Random generator = new Random(); // 객체에서 메서드를 두 번 이상 호출하려면 해당 객체를 변수에 저장해야 합니다.
        System.out.println(generator.nextInt());
        System.out.println(generator.nextInt());
    }
}
