/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    List<String> name = List.of("Peter", "Paul", "Mary");


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
