/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter3;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        BankStatementAnalyzer bankStatementAnalyzer = new BankStatementAnalyzer();

        BankStatementParser bankStatementParser = new BankStatementCSVParser();

        bankStatementAnalyzer.analyze(bankStatementParser);

        HtmlExporter htmlExporter = new HtmlExporter();
        System.out.println(htmlExporter.export(new SummaryStatistics(1.0,2.0,3,4)));
    }
}
