/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        // Not yel implemented
    }
}
